resolver: lts-14.18

packages:
- .

extra-deps:
  - aeson-1.4.6.0
  - ncurses-0.2.16
  - optparse-applicative-0.14.3.0
  - process-1.6.5.0
  - transformers-0.5.6.2
  - yaml-0.11.2.0

nix:
  enable: true
  packages: [ ncurses, zlib ]

